config/routes.rb
Sldemo::Application.routes.draw do |map|
  resources :titles

  resources :companies, :shallow => true do
    member do
      get :terminated_staff, :import_staff, :export_staff, :map
    end
    resources :departments do
      resources :people
    end
    resources :people
  end
  
  resources :departments do
    resources :people
  end
  
  resources :people do
    member do
      get :terminate
    end
    collection do
      get :search
    end
  end

  match '/about' => 'page#about'
  match '/tos' => 'page#tos'
  

  root :to => "companies#index"

end

app/views/shared/_banner.html.erb
<div id='banner'>
	<%= render :partial => "shared/people_search" %>
	<%= render :partial => "shared/sixarm_banner" %>
	<h1><%= image_tag('sixarm-logo.jpg') %> <%= link_to 'SixArm Libraries Demo App', root_path %></h1>
</div>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
<div id="errorExplanation">
  <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
  <ul>
  <% target.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div id='footer'>
	&copy; 2010 <%= link_to 'SixArm', 'http://sixarm.com' %> | Developed by <%= link_to 'Bill Lazar', 'http://billlazar.com' %> | <%= link_to 'TOS/Privacy Policy', '/tos' %> <br/><br/>
	<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/us/">
		<img alt="Creative Commons License" style="border-width:0" src="http://creativecommons.org/images/public/somerights20.png" />
	</a>
</div>

app/views/shared/_people_search.html.erb
<div id='people-search' class='right-banner'>
	<%= form_for @search, :as => :search, :url => search_people_path, :html => {:method => :get} do |f| %>
    <%= f.label :plain_fullname_contains, 'Find Staffer' %>
    <%= f.text_field :plain_fullname_contains, :size => 20 %> 
    <%= f.submit 'Search', :class => 'awesome small green button' %>
		<%= link_to 'Manage Titles', titles_path, :class => 'awesome small blue button', :id => 'manage-titles-link' %>
  <% end %>
</div>

app/views/shared/_sixarm_about.erb
<div id='about-sixarm'>
	<h1>About SixArm</h1>
	<%= render :partial => 'page/sixarm_benefits' %>
	<%= render :partial => 'page/gems_list', :locals => {:list_title => 'SixArm Gems', :gem_list => GEMLISTS[:sixarm_gems]} %>
</div>                                                                                                                     

app/views/shared/_sixarm_banner.html.erb
<div id='six-arm-links' class='right-banner'>
	<%= link_to 'About This Demo', '/about', :style => 'float: left;' %>	SixArm: <%= link_to 'Site', 'http://sixarm.com' %> | <%= link_to 'GitHub', 'http://github.com/sixarm' %>
</div>

app/views/shared/_staff_list_headings.html.erb
<tr>
	<th id='actions-title'></th>
	<th>Name</th>
	<th>Title</th>
	<% if show_phone %>
		<th>Phone</th>
	<% end %>
	<th>Salary</th>
	<th>Hired</th>
	<% if alumni %>
		<th>Terminated</th>
	<% end %>
</tr>