config/routes.rb
Sldemo::Application.routes.draw do |map|
  resources :titles

  resources :companies, :shallow => true do
    member do
      get :terminated_staff, :import_staff, :export_staff, :map
    end
    resources :departments do
      resources :people
    end
    resources :people
  end
  
  resources :departments do
    resources :people
  end
  
  resources :people do
    member do
      get :terminate
    end
    collection do
      get :search
    end
  end

  match '/about' => 'page#about'
  match '/tos' => 'page#tos'
  

  root :to => "companies#index"

end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :company
  has_many :people
  has_one :manager, :class_name => "Person"
  
  validates :name, :presence => true, :uniqueness => true
  validates :company, :presence => true, :associated => true
  
  def to_s
    self.name
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  # GET /departments
  # GET /departments.xml
  def index
    # department for a company
    if params[:company_id]
      @company = Company.find(params[:company_id])
      @departments = @company.departments
    # all departments
    else
      @departments = Department.all
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @departments }
    end
  end

  # GET /departments/1
  # GET /departments/1.xml
  def show
    @department = Department.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @department }
    end
  end

  # GET /departments/new
  # GET /departments/new.xml
  def new
    @department = Department.new
    if params[:id]
      @department.company = Company.find(params[:id])
      @company_people = @department.company.people.active
    end

    respond_to do |format|
      format.html { render :layout => false } # new.html.erb
      format.xml  { render :xml => @department }
    end
  end

  # GET /departments/1/edit
  def edit
    @department = Department.find(params[:id])
    @company_people = @department.company.people.active
  end

  # POST /departments
  # POST /departments.xml
  def create
    params[:department][:company_id] = 1
    @department = Department.new(params[:department])
    @department.manager = Person.find(params[:department][:manager_id])
    @company_people = @department.company.people.active

    respond_to do |format|
      if @department.save
        format.html { redirect_to(companies_path, :notice => 'Department was successfully created.') }
        format.xml  { render :xml => @department, :status => :created, :location => @department }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @department.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /departments/1
  # PUT /departments/1.xml
  def update
    @department = Department.find(params[:id])

    respond_to do |format|
      if @department.update_attributes(params[:department])
        format.html { redirect_to(companies_path, :notice => 'Department was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @department.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.xml
  # TODO Must add 'reassign staffers' functionality
  def destroy
    @department = Department.find(params[:id])
    @department.destroy

    respond_to do |format|
      format.html { redirect_to(departments_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_department.html.erb
<tr class="<%= cycle("even", "odd") -%>">
	<td><%= link_to department.name, edit_department_path(department), :title => 'Edit' %></td>
	<td><%= department.manager.full_name %></td>
	<td class="">
		<%= link_to 'Staffers', people_path(:department_id => department), :remote => true, :class => 'staffers-link' %>
		<% if department.people.count == 0 %>
			<%= link_to 'X', department, :confirm => 'Are you sure?', :method => :delete, :title => 'Delete' %>
		<% end %>
	</td>
</tr>

app/views/departments/_form.html.erb
<%= render "shared/error_messages", :target => form %>

<div class="field">
	<%= form.label :name %><br />
	<%= form.text_field :name %>
</div>
<div class="field">
	<%= form.label :manager_id, 'Manager' %><br />
	<%= form.select :manager_id, options_from_collection_for_select(@company_people, 'id', 'list_name', @department.manager_id), { :include_blank => 'None Yet' } %>
</div>
<div class="actions">
	<%= form.submit %> <%= link_to 'Cancel', companies_path, :class => 'canceler' %>
</div>

app/views/departments/edit.html.erb
<h1>Editing <%= @department %></h1>

<%= form_for @department do |form| %>
	<%= render form %>
<% end %>

app/views/departments/index.html.erb
<h1><%= @company %> Departments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Manager</th>
    <th></th>
  </tr>

	<%= render :partial => 'departments/department', :collection => @departments %>
</table>
<br />

<%= link_to 'Add Department', new_department_path(:id => @company.id), :class => 'awesome blue button' %>

app/views/departments/new.html.erb
<% if @department.company %>
	<h1>New Department in <%= @department.company %></h1>
<% else %>
	<h1>New Department</h1>
<% end %>

<%= form_for Department.new do |form| %>
	<%= render form %>
<% end %>

app/views/departments/show.html.erb
<h1><%= @department.name %></h1>
<% show_for @department do |d| %>
	<%= d.association :manager, :using => :full_name %>
	<% d.association :people, :label => 'Staffers', :label_tag => 'h2' do |person| %>
		<li>
			<span class='actions'>
				<%= link_to('E', edit_person_path(person), :title => 'Edit') %>
				<% if deletable %>
					<%= link_to 'X', terminate_person_path(person), :confirm => 'Terminate this staffer?', :title => 'Terminate this staffer?' %>
					<% end %>
			</span>
			<span><%= link_to(person.list_name, person) %></span>
			<span><%= person.title %></span>
			<span><%= person.phone %></span>
			<span><%= number_to_currency(person.salary, :precision => 0) %></span>
			<span><%= person.hired %></span>
			<% if person.terminated %>
		  	<span><%= person.terminated %></span>
			<% end %>
		</li>
	<% end %>
<% end %>

<%= link_to 'Edit', edit_department_path(@department), :class => 'button' %> 
<%= link_to 'Back', departments_path, :class => 'button' %>