config/routes.rb
Sldemo::Application.routes.draw do |map|
  resources :titles

  resources :companies, :shallow => true do
    member do
      get :terminated_staff, :import_staff, :export_staff, :map
    end
    resources :departments do
      resources :people
    end
    resources :people
  end
  
  resources :departments do
    resources :people
  end
  
  resources :people do
    member do
      get :terminate
    end
    collection do
      get :search
    end
  end

  match '/about' => 'page#about'
  match '/tos' => 'page#tos'
  

  root :to => "companies#index"

end

app/models/company.rb
require 'csv'

class Company < ActiveRecord::Base
  has_many :departments
  has_many :people
  
  validates :name, :presence => true, :uniqueness => true, :length => { :minimum => 8 }
  validates :city, :presence => true
  validates :state, :presence => true, :length => { :in => 2..2 }
  validates :incorporation_year, :presence => true
  
  def to_s
    self.name
  end
  
  def from_csv(csvfile)
    cur = 0
    CSV.open(csvfile, 'r') do |row|
      if cur > 0 # skip first row, has col names
      else
        cols = row
      end
    end
  end
  
  def to_csv
    cur_csv = 'tmp/' + self.name + '-staff-export-' + Date.today.to_s + '.csv'
    begin
      expcnt = CSV.generate do |csv|
        csv << ['name', 'department', 'title', 'salary', 'phone', 'favorite color','hired', 'terminated']
        self.people.each do |p|
          csv << [p.list_name, p.department.name, p.title, p.salary, p.phone, p.favorite_color, p.hired_on.to_s, p.terminated_on.to_s]
        end
        send_data(expcnt, :type=> 'text/csv; charset=utf-8; header=present', :filename => cur_csv)
      end
      return {:res => 'success', :msg => 'Wrote export file: ' + cur_csv}
    rescue Exception => exc
      return {:res => 'error', :msg => 'Problem: Could not write export file, ' + exc.message}
    end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :get_co, :except => [:index, :create]
  
  # GET /companies
  # GET /companies.xml
  def index
    @company = Company.first
    @departments = @company.departments

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.xml
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @company }
    end
  end

  def import_staff
    respond_to do |format|
      format.html { render :layout => false }
      format.xml  { render :xml => @company }
    end
  end
  
  def export_staff
    @exp = @company.to_csv
    respond_to do |format|
      format.html { render :layout => false }
      format.xml  { render :xml => @company }
    end
  end
  
  def terminated_staff
    @terminated = @company.people.terminated
    respond_to do |format|
      format.html { render :layout => false }
      format.xml  { render :xml => @terminated }
    end
  end
  
  def map
    respond_to do |format|
      format.html { render :layout => false }
      format.xml  { render :xml => @terminated }
    end
  end
  
  # GET /companies/new
  # GET /companies/new.xml
  def new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @company }
    end
  end

  # GET /companies/1/edit
  # Assumes will be called from Ajax link
  def edit
    render :layout => false
  end

  # POST /companies
  # POST /companies.xml
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to(@company, :notice => 'Company was successfully created.') }
        format.xml  { render :xml => @company, :status => :created, :location => @company }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @company.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.xml
  def update

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to(companies_path, :notice => @company.name + ' was successfully updated.') }
        format.js   { redirect_to(companies_path, :notice => @company.name + ' was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.js   { render :action => "edit", :layout => false }
        format.xml  { render :xml => @company.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.xml
  def destroy
    @company.destroy

    respond_to do |format|
      format.html { redirect_to(companies_url) }
      format.xml  { head :ok }
    end
  end
  
  protected
  def get_co
    @company = Company.find(params[:id])
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
  def fav_colors_list(c)
    fc = []
    c.people.count(:group => :favorite_color).each_pair do |k,v|
      fc << k + ': ' + v.to_s
    end
    fc.to_sentence
  end
end

app/views/companies/_company.html.erb
<tr>
  <td><%= link_to company.name, edit_company_path(company), :title => 'Edit' %> <%# link_to 'X', company, :confirm => 'Are you sure?', :method => :delete, :title => 'Delete' %></td>
  <td><%= company.city %>, <%= company.state %></td>
  <td><%= company.incorporation_year %></td>
  <!-- <td><%# link_to 'Departments', structure_company_path(company) %></td> -->
  <td><%= link_to 'Alumni', terminated_staff_company_path(company), :class => 'button' %></td>
	<td><%= link_to 'Manage Titles', titles_path, :class => 'button' %></td>
</tr>

app/views/companies/_company_toolbar.html.erb
<p class='toolbar'>
	<%= link_to 'Alumni List', terminated_staff_company_path(@company), :remote => true, :class => 'remoter first awesome small blue button' %>
	<%= link_to 'Import Staffers', import_staff_company_path(@company), :remote => true, :class => 'remoter awesome small blue button', :title => 'Coming Soon' %>
	<%= link_to 'Export Staffers', export_staff_company_path(@company), :remote => true, :class => 'last remoter awesome small blue button', :title => 'Coming Soon' %>
</p>

app/views/companies/_departments.html.erb
<h2>Departments</h2>
<table>
  <tr>
    <th>Name</th>
    <th>Manager</th>
    <th></th>
  </tr>

	<%= render :partial => 'departments/department', :collection => departments %>
</table>

app/views/companies/_form.html.erb
<%= render "shared/error_messages", :target => @company %>

<div class="field">
	<%= form.label :name %><br />
	<%= form.text_field :name %>
</div>
<div class="field">
	<%= form.label :city %><br />
	<%= form.text_field :city %>
</div>
<div class="field">
	<%= form.label :state %><br />
	<%= form.text_field :state %>
</div>
<div class="field">
	<%= form.label :incorporation_year, 'Incorporated' %><br />
	<%= form.text_field :incorporation_year %>
</div>
<div class="actions">
	<%= form.submit :remote => true %> <%= link_to 'Cancel', companies_path, :remote => true, :class => 'canceler' %>
</div>

app/views/companies/edit.html.erb
<h1>Editing <%= @company -%> Info</h1>

<%= form_for @company do |form| %>
	<%= render form %>
<% end %>

app/views/companies/edit.js.erb
<h1>Editing Company <%= @company -%></h1>

<%= render 'form' %>

app/views/companies/export_staff.html.erb
<h1>Export <%= @company %> Staffers</h1>
<%# link_to 'Save as Download', department_path(:id => @company.id), :remote => true, :class => 'big awesome blue button remoter' %>
<div id='exp_results' class='<%= @exp[:res] %>'><%= @exp[:msg] %></div>
<table id='export-list'>
	<%= render :partial => 'shared/staff_list_headings', :locals => {:alumni => true, :show_phone => false} %>
	<%= render :partial => 'people/short_line', :locals => {:people => @company.people, :deletable => false, :show_phone => false} %>
</table>

app/views/companies/import_staff.html.erb
Test

app/views/companies/index.html.erb
<div id='company-wrapper'>
	<div id='primary'>
		<h1><%= link_to @company.name, edit_company_path(@company), :remote => true, :class => 'remoter', :title => 'Edit' %></h1>
		<%= render :partial => 'company_toolbar' %>
		<div class='company-data' id='<%= @company.name %>'>
			<p>Headquartered in <strong><span id='<%= @company.city %>' class='company-city'><%= @company.city %></span>, <span id='<%= @company.state %>' class='company-state'><%= @company.state %></span></strong> (<%= link_to 'Map', map_company_path(@company), :remote => true, :class => 'remoteMap' %>)</p>
			<p>Incorporated in <strong><%= @company.incorporation_year %></strong></p>
			<p><strong>Staff favorite colors</strong> are <%= fav_colors_list(@company) %></p>
		</div>
		
		<%= render :partial => 'departments', :locals => {:departments => @departments} %>
		<br />

		<%= link_to 'Add Department', new_department_path(:id => @company.id), :remote => true, :class => 'awesome medium blue button remoter' %>

		<%# link_to 'Add Company', new_company_path, :class => '' %>
	</div>
	<div id='secondary'>
		<%= render :partial => 'shared/sixarm_about' %>
	</div>
</div>

app/views/companies/map.html.erb
<div id="map"></div>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= form_for Company.new do |form| %>
	<%= render form %>
<% end %>

app/views/companies/show.html.erb
<h1><%= @company.name %></h1>

<% show_for @company do |c| %>
  <%= c.attribute :city %>
  <%= c.attribute :state %>
  <%= c.attribute :incorporation_year %>
<% end %>


<%= link_to 'Edit', edit_company_path(@company), :class => 'button' %> 
<%= link_to 'Back', companies_path, :class => 'button' %>

app/views/companies/terminated_staff.html.erb
<h1><%= @company %> Alumni</h1>

<table>
	<%= render :partial => 'shared/staff_list_headings', :locals => {:alumni => true, :show_phone => false} %>
	<%= render :partial => 'people/short_line', :locals => {:people => @terminated, :deletable => false, :show_phone => false} %>
</table>