config/routes.rb
Sldemo::Application.routes.draw do |map|
  resources :titles

  resources :companies, :shallow => true do
    member do
      get :terminated_staff, :import_staff, :export_staff, :map
    end
    resources :departments do
      resources :people
    end
    resources :people
  end
  
  resources :departments do
    resources :people
  end
  
  resources :people do
    member do
      get :terminate
    end
    collection do
      get :search
    end
  end

  match '/about' => 'page#about'
  match '/tos' => 'page#tos'
  

  root :to => "companies#index"

end

app/models/title.rb
class Title < ActiveRecord::Base
  has_many :people
  validates :title, :presence => true, :length => { :within => 3..20 }
  
  def to_s
    self.title
  end
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  # GET /titles
  # GET /titles.xml
  def index
    @titles = Title.all

    respond_to do |format|
      format.html #{render :layout => false} # index.html.erb
      format.xml  { render :xml => @titles }
    end
  end

  # GET /titles/1
  # GET /titles/1.xml
  def show
    @title = Title.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @title }
    end
  end

  # GET /titles/new
  # GET /titles/new.xml
  def new
    @title = Title.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @title }
    end
  end

  # GET /titles/1/edit
  def edit
    @title = Title.find(params[:id])
  end

  # POST /titles
  # POST /titles.xml
  def create
    @title = Title.new(params[:title])

    respond_to do |format|
      if @title.save
        format.html { redirect_to(@title, :notice => 'Title was successfully created.') }
        format.xml  { render :xml => @title, :status => :created, :location => @title }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @title.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /titles/1
  # PUT /titles/1.xml
  def update
    @title = Title.find(params[:id])

    respond_to do |format|
      if @title.update_attributes(params[:title])
        format.html { redirect_to(@title, :notice => 'Title was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @title.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /titles/1
  # DELETE /titles/1.xml
  def destroy
    @title = Title.find(params[:id])
    @title.destroy

    respond_to do |format|
      format.html { redirect_to(titles_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/views/titles/_form.html.erb
<%= form_for(@title) do |f| %>
	<%= render "shared/error_messages", :target => @title %>

  <div class="field">
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %> <%= link_to 'Cancel', titles_path %>
  </div>
<% end %>

app/views/titles/edit.html.erb
<h1>Editing Title: <%= @title.title %></h1>

<%= render 'form' %>

app/views/titles/index.html.erb
<h1>Staff Titles</h1>

<p><%= link_to 'Add Title', new_title_path, :class => 'button' %></p>

<table>
  <tr>
    <th></th>
    <th>Title</th>
  </tr>

<% @titles.each do |title| %>
  <tr>
    <td class='actions'>
			<% if title.people.count == 0 %>
			<%= link_to 'X', title, :confirm => 'Are you sure?', :method => :delete %>
			<% end %>
		</td>
    <td><%= link_to title.title, edit_title_path(title), :title => 'Edit' %></td>
  </tr>
<% end %>
</table>

<br />

<p><strong>Note:</strong> Titles currently used by staff cannot be deleted.</p>

app/views/titles/new.html.erb
<h1>New Title</h1>

<%= render 'form' %>

app/views/titles/show.html.erb
<p>
  <b>Title:</b>
  <%= @title.title %>
</p>


<%= link_to 'Edit', edit_title_path(@title), :class => 'button' %> 
<%= link_to 'Back', titles_path, :class => 'button' %>